services:
  - type: web
    name: extinct-mammals
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn extinct_mammals_django.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
    
databases:
  - name: extinct-mammals-db
    databaseName: extinct_mammals
    user: extinct_mammals